DELETE http://localhost:3001/api/persons/1

#### Add user

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Calvin Große",
    "number": "0494330608-n"
}

### info
GET http://localhost:3001/